### ISSUE TITLE
Add travis

### ISSUE THREAD

**Issue by PaliwalSparsh** [PaliwalSparsh/react-games-lego#10]
We need to add CI to our library so that we can run test and build for each PR.

**Comment by abh3po** [comment]
will stuff in the Readme suffice? for starters? can i be assigned to this?

**Comment by PaliwalSparsh** [comment]
Yup sure you can pick this up. You just need to have node and npm installed. Then install the dependencies with `npm install` and then `npm start` would do everything. You can refer this - 
[https://github.com/PaliwalSparsh/dots-and-boxes/blob/master/.travis.yml](https://github.com/PaliwalSparsh/dots-and-boxes/blob/master/.travis.yml)

and maybe more fancy things.
