### ISSUE TITLE
Create demo webpage

### ISSUE THREAD

**Issue by PaliwalSparsh** [PaliwalSparsh/react-games-lego#5]

**Comment by abh3po** [comment]
would it be a part of this repo? how do we go about this?

**Comment by PaliwalSparsh** [comment]
Yup it would be a part of the repo. They would be present there as examples of how to use the library. Also, while we are uploading library to package manager we will just add these examples in the .npmignore file so it wont be an issue.

**Comment by PaliwalSparsh** [comment]
Duplicate #24
